[tool.black]
target-version = ["py38"]

[tool.coverage.run]
relative_files = true

[tool.coverage.report]
precision = 2
show_missing = true
skip_covered = true
exclude_lines = ["if __name__ == .__main__.:", "def __str__", "def __repr__", "pragma: no cover"]

[tool.isort]
line_length = 88
force_grid_wrap = "0"
multi_line_output = "3"
use_parentheses = true
combine_as_imports = true
known_first_party = ["v8_server"]
known_third_party = ["pytest, recommonmark"]
include_trailing_comma = true
lines_after_imports = "2"
